### ISSUE TITLE
Rule E Removals

### ISSUE THREAD

**Issue by Snorrrlax** [perezdev/CMVModBot#1] opened 2017-11-07 23:20 UTC
Rule E requires that OPs respond to some comments within the first 3 hours of posting. 

We'd like CMVModBot to automatically remove posts that are 3 hours old if OP made no comments, and send a modmail to remind a mod to make a note of it (unless you can figure out a way to have CMVModBot add a SnooNote itself).

**Comment by Snorrrlax** [comment] 2017-11-16 12:26
The bot should automatically remove a post that's 3 hours old if there's 3+ top level comments and OP hasn't replied to any of them. 

The reason why we've added the condition of 3+ comments is for cases where the post received one or two low-effort, irrelevant responses, which the OP shouldn't be punished for ignoring. Setting the level at 3+ means the chances are at least one comment is worthy of a reply, and if OP hasn't done so in 3 hours, the post should be removed. These 3+ comments must be "top level" (i.e. direct responses to the post) to avoid situations where someone makes a low-effort comment, another user replies to that, and so on, which is still irrelevant to the OP despite being 3+.

Sometimes a post needs approval before it goes live (new accounts/accounts with low karma/fresh topic friday) - the timer for 3 hours should start upon approval in these cases, not time of posting. 

A SnooNote for Rule E should be added if possible, but if not, then a modmail should be sent to notify mods that a note is needed. 

When removing a post for Rule E, the bot should also make, distinguish & sticky this comment:

> Sorry, username – your submission has been removed for breaking Rule E:
>
> > Only post if you are willing to have a conversation with those who reply to you, and are available to start doing so within 3 hours of posting. If you haven't replied within this time, your post will be removed. [See the wiki for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_e).
>
> If you would like to appeal, please respond substantially to some of the arguments people have made, and then [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&subject=Rule+E+Appeal+appypollylogiess&message=appypollylogiess+would+like+to+appeal+the+removal+of+%5Bhis/her+post%5D(https://www.reddit.com/r/changemyview/comments/7d0v3w/cmv_virginity_may_be_just_a_social_construct_but/)+because...).

**Comment by perezdev** [comment] 2018-01-20 03:30
All of these requirements have been implemented, minus the snoonotes. That requirement is possible, but I'm still working on it. Going to close this and refer #5 for the additional requirements.

**Closed as completed by perezdev** 2018-01-20 03:30 UTC

**Comment by Snorrrlax** [comment] 2018-01-20 13:46
Thanks! Once SnooNotes is added, we could start running the bot in the sub while you work on remaining issues?

**Comment by perezdev** [comment] 2018-01-20 16:52
@Snorrrlax Yeah, for sure. Do you think it would be possible to get handful of testers and test on /r/CMVModBotTest for a week once I'm ready? It would be good to run the bot through to eliminate any large bugs and make sure it's working as intended.

**Comment by Snorrrlax** [comment] 2018-01-20 16:58
Yeah I'm sure I could get a few mods to help! Could you make a post in r/CMVModBotTest to explain what you'd like us to do?
